### ISSUE TITLE
Publish on Packagist

### ISSUE THREAD

**Issue by jdoubleu** [OttoAndras/typo3-csp#3]
Could you please publish this extension on [Packagist](https://packagist.org/)?

So far I have to add it as a repository to my `composer.json`:
```JSON
{
    "repositories": [
        { "type": "git", "url": "https://github.com/OttoAndras/typo3-csp.git" }
    ],
    ...
}
```

**Comment by OttoAndras** [comment]
I will do this this week! Sorry for the late response, I was abroad.

**Comment by OttoAndras** [comment]
I've made it.
